# -*- coding: utf-8 -*-
"""final exam ML .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcxB94u8PgwUJM2duBC0kQy3gLe5CyEx
"""

# Install necessary libraries
!pip install fer opencv-python matplotlib

# Ensure tensorflow is installed for GPU usage (fer depends on it)
!pip install tensorflow

print("Libraries installed successfully!")

import cv2
from fer.fer import FER  # Corrected import statement
import matplotlib.pyplot as plt
from google.colab import files
import os

# Input and Output video paths
input_video_path = '/content/20260608_13_48_48_Pro08.mov' # Updated video path
output_video_path = '/content/emotion_detected_video.mp4'

print(f"Input video: {input_video_path}")

# Initialize the FER detector
# The 'mtcnn' detector is generally faster and more accurate than 'haar' and 'dlib'
# It leverages TensorFlow which can use the GPU.
detector = FER(mtcnn=True)

# Open the video file
cap = cv2.VideoCapture(input_video_path)

# Check if video opened successfully
if not cap.isOpened():
    print(f"Error: Could not open video file {input_video_path}")
    exit()

# Get video properties
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))
fourcc = cv2.VideoWriter_fourcc(*'mp4v') # Codec for .mp4 output

print(f"Video properties: Width={frame_width}, Height={frame_height}, FPS={fps}")

# Create a VideoWriter object to save the output video
out = cv2.VideoWriter(output_video_path, fourcc, fps, (frame_width, frame_height))

frame_count = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break # Break if no more frames

    # Convert frame to RGB for FER (OpenCV reads BGR)
    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # Detect emotions in the frame
    # This step is computationally intensive and benefits from GPU
    result = detector.detect_emotions(rgb_frame)

    # Draw bounding boxes and emotion labels
    for face in result:
        (x, y, w, h) = face['box']
        emotions = face['emotions']

        # Get the dominant emotion
        dominant_emotion = max(emotions, key=emotions.get)

        # Draw rectangle (green color)
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2) # Green BGR

        # Put text (emotion label in green)
        cv2.putText(frame, dominant_emotion, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2) # Green BGR

    # Write the processed frame to the output video
    out.write(frame)

    frame_count += 1
    if frame_count % (fps * 5) == 0: # Print progress every 5 seconds of video
        print(f"Processed {frame_count / fps:.0f} seconds...")

# Release video objects
cap.release()
out.release()
# cv2.destroyAllWindows() # Removed this line as it causes an error in Colab

print(f"Video processing complete. Output saved to {output_video_path}")

# Provide download link
if os.path.exists(output_video_path):
    print("Downloading the processed video...")
    files.download(output_video_path)
else:
    print(f"Error: Output video file not found at {output_video_path}")